#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>

/*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*
* Purpose: This program is used to assign student into group (maximum group of thee and remaining student will be divided in to group of two).
*           Accept maximum 33 students and will generates unique speudorandom numbers for each, and divides them into groups.
*
*
* Program name: ANGroupAssignment.c
*
* Invocation: ./ANGroupAssignment
*
* Variables:
*   int GenUniqRanNum(min, max, UsedNum[]):    Function called to generate unique random numbers
*   int Snum:                                  Toltal student in class.
*   int group_of_three:                        Total groups with 3 students.
*   int group_of_two:                          Total groups with 2 students.
*   int group_total:                           Total number of groups (including group of 3 and group of 2)
*   bool UsedNum[]:                            Used to track which numbers have been used.
*   int groups_display[group_total][4]:        2D array to store group number and students.
*   int group_index:                           Index used to loop through group assignments.
*   int student_position:                      Index used to assign students within each group.
*
* Functions called: GenUniqRanNum
*
* Written by: An Nguyen
* Date: 10/13/2024
*
* Modification: None
*
* Special notes: This program accept a maximum 33 students.
*
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
*/


int GenUniqRanNum(int min, int max, bool UsedNum[])
/*
 This function takes 3 arguments, the minimum value for
 the random number to be generated, the maximum value for
 the random number to be generated, and an array of numbers
 that have already been used to avoid duplication.
 
 Another way to look at this is generation of a random number
 with no repeats.  This is a useful function that can be
 used to generate any range of unique random numbers.
  
 Variables are:
    int min - the smallest acceptable random
    int max - the largest acceptable number
    bool UsedNum[] - and array of used numbers, used as a logical
                     to test whether a generated number has already
                     been used to prevent duplication.
    int RandomNum -  the number generated by a call to rand()
    bool Debug - A switch to turn on or off debug prints
 
 */
{
    int RandomNum, Cycles;
    bool Debug = {false};
    // bool Debug = {true};
    if (Debug)
    {
        printf("\t\t\tmin = %d, max = %d\n",max, min);
    }
    Cycles = 0;
    do
    {
        Cycles++;
        RandomNum = rand() % (max - min + 1) + min;
        /*
         Call the random function to generate a number, then use
         the modulo operator to limit the range of the numbers
         between max and min inclusive (inclusive means you expect
         both max and min as acceptable values.  Exclusive ranges
         would be less than max and more than min.
         
         Note:  We do not seed the random number generator here
         because if we need to run a test set of repeated random
         numbers we wouldn't want the function to change the seed
         so we seed the random number generator in the main program.
    */
    }
    while (UsedNum[RandomNum - 1]);  // The do/while loop executes as long as
                                                                    // the condition is true.
                                                                    // Exit the loop when we get a false (0)
                                                                    // Indicating that the number has NOT been used
                                                                    //   Array starts all false (0)
    
    UsedNum[RandomNum - 1] = true;  // When an unused number is found, set
                                                                  // the value at that number to true indicating
                                                                // that value is now used.
    printf("\t\t\tNumber of cycles to get the number = %d\n",Cycles);
    
    return RandomNum;
}                   //      End of GenUniqRanNum function
int main()
/*
        This program simply calls the function to generate a unique random
        number.  It then prints out the random numbers as they are generated
        
        Modify this to store the numbers in a 10x2 array with each row
        representing one group.  Handling an odd number of students is
        a slightly different challenge.
 
        Variables:
            int LCount, LCount2 - the loop countera
            int RandomNum - the value returned by the function
            int Snum - the number of students in the class
            int Groups[][] - Group member numbers
            bool UsedNum[] - the array of used numbers
            bool Debug - the switch to turn off/on Debug printing
 */
{
    short int LCount, LCount2;
    short int RandomNum;
    short int Snum;
    int Groups[11][3];                          // Max allowed is 33 students
    bool UsedNum[33] = {false};
    bool Debug = {true};                            // Turn on debug printing
    // bool Debug = {false};    // Turn off debug printing

    // SET UP FOR MAXIMUM GROUP OF THREE
    short int group_of_three;
    short int remaining_student;
    short int group_of_two; 
    short int group_total;
    short int UsedNum_index;

    // 2d array for groups displaying at the end
    short int groups_display[group_total][4];

    // SET UP TO PERFROM ASSIGN GROUP OF THREE 
    short int group_index;
    short int student_position;


    printf("Please tell me the number of students >> ");
    scanf("%d",&Snum);
    while (getchar() != '\n');      // Clean out the input buffer
    // Initialize random seed with current time
    srand(time(NULL));
	// srand(0);        // This gives the same sequence of
                                                    // pseudo-random numbers for testing
    if (Debug)
    {
        //      This is just for fun!  Number of seconds since Jan 1, 1970
        printf("Time(NULL) = %ld\n",time(NULL));
    }
    // Generate and print Snum unique random numbers in the range 1-20
    for (LCount = 0; LCount < Snum; LCount++)
    {
        RandomNum = GenUniqRanNum(1, Snum, UsedNum);
        printf("Unique random number %d: %d\n", LCount + 1, RandomNum);
        if(Debug)
        {
            printf("List of values stored:\n");
            printf("Note: the array is boolean so it's 0 or !0 (Usually 1)\n"); 
            for (LCount2 = 0; LCount2 < Snum; LCount2++)
            {
                printf("Value of UsedNum[%d] = %d\n",  LCount2, UsedNum[LCount2]);
            }                       // End of array printing loop (LCount2)
        }                           // End of Debug print
    }                               // End of for loop

    // reset UsedNum array
    for (UsedNum_index = 0; UsedNum_index < Snum; UsedNum_index++)
    {
        UsedNum[UsedNum_index] = false;
    }

    // PERFORM MAXIMUM GROUP OF THREE 
    group_of_three = Snum / 3;
    remaining_student = Snum % 3; 

    if(remaining_student == 1) 
    {
        group_of_three--;
        remaining_student = 4;
        group_of_two = remaining_student / 2;
    } 
    else if(remaining_student == 2) 
    {
        group_of_two = remaining_student / 2;
    } 
    else 
    {
        group_of_two = 0;
    }

    group_total = group_of_three + group_of_two;

    printf("Number of group of 3: %d\n", group_of_three);
    printf("Number of group of 2: %d\n", group_of_two);
    printf("Group total: %d\n", group_total);

    // assigning for groups of three
    for (int group_index = 0; group_index < group_of_three; group_index++)
    {
        printf("debug: here in assigning threes.\n");
        groups_display[group_index][0] = group_index + 1;
        for (student_position = 1; student_position <= 3; student_position++)
        {
            groups_display[group_index][student_position] = GenUniqRanNum(1, Snum, UsedNum);
        }
    }

    // assigning for groups of two
    for (group_index = group_of_three; group_index < group_total; group_index++)
    {
        printf("debug: here in assigning twos.\n");
        groups_display[group_index][0] = group_index + 1;
        for (student_position = 1; student_position <= 2; student_position++)
        {
            groups_display[group_index][student_position] = GenUniqRanNum(1, Snum, UsedNum);
        }
        groups_display[group_index][3] = 0;
    }

    
    // // // Print the groups in format
    printf("Group\tStudent 1\tStudent 2\tStudent 3\n");
    for (group_index = 0; group_index < group_total; group_index++) 
    {
        printf("%d\t", groups_display[group_index][0]);                                    //assign col0 with group name (group number)
        for (student_position = 1; student_position <= 3; student_position++)       // start to assign value from group_array to student1,2,3 col
        {
            if (groups_display[group_index][student_position] != 0)                         
            {
                printf("%d\t\t", groups_display[group_index][student_position]);           
            } 
            else 
            {
                printf("\t\t");
            }
        }
        printf("\n");
    }
    
    return (0);
}